#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "autobrr"
name = "Autobrr"
description.en = "Modern, easy to use download automation for torrents and usenet"
description.fr = "Automatisation de téléchargement pour les torrents et Usenet"

version = "1.76.0~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0-only"
website = "https://autobrr.com/"
code = "https://github.com/autobrr/autobrr"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/autobrr"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/autobrr/autobrr/releases/download/v1.76.0/autobrr_1.76.0_linux_x86_64.tar.gz"
    amd64.sha256 = "4e3198760bc87c9eff77bebc84f06e045205a374275e0620608654f2cc629280"
    arm64.url = "https://github.com/autobrr/autobrr/releases/download/v1.76.0/autobrr_1.76.0_linux_arm64.tar.gz"
    arm64.sha256 = "67e85a6664082fe6868e05e8c537f40c4d42b3b5e2266b852d2b8138a57b48c5"
    armhf.url = "https://github.com/autobrr/autobrr/releases/download/v1.76.0/autobrr_1.76.0_linux_arm.tar.gz"
    armhf.sha256 = "5c759e55d2c1f4c442e4ba6dd8770f1be9fd92708971b41800b2a28b00589322"
    in_subdir = false
    extract = true
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^autobrr_.*_linux_x86_64.tar.gz$"
    autoupdate.asset.arm64 = "^autobrr_.*_linux_arm64.tar.gz$"
    autoupdate.asset.armhf = "^autobrr_.*_linux_(arm|armv6).tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
