#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "autobrr"
name = "Autobrr"
description.en = "Easy to use download automation for torrents and usenet"
description.fr = "Automatisation de téléchargement pour les torrents et Usenet"

version = "1.87.0~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0-only"
website = "https://autobrr.com/"
code = "https://github.com/autobrr/autobrr"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/autobrr"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/autobrr/autobrr/releases/download/v1.87.0/autobrr_1.87.0_linux_x86_64.tar.gz"
    amd64.sha256 = "3ae137ff7d803af0ae9c8ef4d30a235e83a1d6f8b7484c6eb76ffb77ab3342d2"
    arm64.url = "https://github.com/autobrr/autobrr/releases/download/v1.87.0/autobrr_1.87.0_linux_arm64.tar.gz"
    arm64.sha256 = "1706086f345750c37cf64d4426c1bff0dbbaf1f124ddc4376599b381056b3e09"
    armhf.url = "https://github.com/autobrr/autobrr/releases/download/v1.87.0/autobrr_1.87.0_linux_arm.tar.gz"
    armhf.sha256 = "3a321a71a4ef9250b0c5dc29f9eac24bd2ffb06f3b1412e4f6e3f30b0c7304c6"
    in_subdir = false
    extract = true
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^autobrr_.*_linux_x86_64.tar.gz$"
    autoupdate.asset.arm64 = "^autobrr_.*_linux_arm64.tar.gz$"
    autoupdate.asset.armhf = "^autobrr_.*_linux_(arm|armv6).tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
