#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "autobrr"
name = "Autobrr"
description.en = "Modern, easy to use download automation for torrents and usenet"
description.fr = "Automatisation de téléchargement pour les torrents et Usenet"

version = "1.75.0~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0-only"
website = "https://autobrr.com/"
code = "https://github.com/autobrr/autobrr"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/autobrr"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/autobrr/autobrr/releases/download/v1.75.0/autobrr_1.75.0_linux_x86_64.tar.gz"
    amd64.sha256 = "9eb47d388b6798d04eaf728a4d6df66143448672cd40bc5cb47390ee902d7954"
    arm64.url = "https://github.com/autobrr/autobrr/releases/download/v1.75.0/autobrr_1.75.0_linux_arm64.tar.gz"
    arm64.sha256 = "048755984c93f7bf552711c836c3dea817d97a1dec0a63ba2263c8beb2eeae99"
    armhf.url = "https://github.com/autobrr/autobrr/releases/download/v1.75.0/autobrr_1.75.0_linux_arm.tar.gz"
    armhf.sha256 = "c51f2e53c9c3026f1c6d38065f161ed1b34403e53daad6faca8fd675a6cae4e1"
    in_subdir = false
    extract = true
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^autobrr_.*_linux_x86_64.tar.gz$"
    autoupdate.asset.arm64 = "^autobrr_.*_linux_arm64.tar.gz$"
    autoupdate.asset.armhf = "^autobrr_.*_linux_(arm|armv6).tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
